# Author: Anubhav Joshi
"""
Building a BERT sequence-classification model with fine tuning strategies
for the "prompt family" of methods. 

Strategy        |      Where the soft prompt lives     |    Reparameterized (update raw embedding or MLP weights)
-------------------------------------------------------------------------------------------------------------
prompt-tuning   | prepended to the input embeddings only (layer 0) | no - raw embeddings trained directly
prefix-tuning   | prepended to the K/V of EVERY transformer layer  | yes - 2 layer MLP
p-tuning        | prepended to the input embeddings only (layer 0) | yes - LSTM/MLP "prompt encoder"
p-tuning-v2     | prepended to K/V of EVERY transformer layer      | no - per layer prefix trained directly

prompt-tuning (Lester et al. 2021) and p-tuning (Liu et al 2021) are both shallow: The soft (added) tokens
only touch the first embedding layer, so every later layer sees them just like normal input embeddings.
p-tuning twwist over prompt-tuning is that the osft embeddings are produced by a small MLP (prompt encoder)
instead of trained directly.

prefix tuning (Li and Liang 2021) and p-tuning-v2 (Liu et al. 2022) are both deep: The soft token is injected
into the attention K/V of every transfomer layer. prefix tuning reparameterized the prefix through an MLP,
while p-tuning-v2 removes that MLP and optimizes the per-layer prefix vectors directly.
While point is that training 20 raw embedding vectors directly is unstable, and squeezing them through
a narrow MLP actos as a regularizer that smooths the optimization landscape.
"""

import logging
from transformers import AutoModelForSequenceClassification
from src.utils import NUM_LABELS

logger = logging.getLogger(__name__)

PROMPT_FAMILY_STRATEGIES = ["prompt-tuning", "prefix-tuning", 'p-tuning', "p-tuning-v2"]

def _build_prompt_tuning_config(model_name, num_virtual_tokens, prompt_tuning_init, 
                                prompt_tuning_init_text):
    """
    prompt-tuning: num_virtual_tokens trainable "soft prompt" embeddings
    are prepended to the input embeddings.
    """
    from peft import PromptTuningConfig, PromptTuningInit, TaskType

    init_kwargs = {}
    if prompt_tuning_init == "text":
        # TEXT init sees the soft prompt from the embeddings of a real sentence instead of 
        # random noise - needs the same tokenizer the base model uses so the token ids line up.

        init = PromptTuningInit.TEXT
        init_kwargs["prompt_tuning_init_text"] = (
            prompt_tuning_init_text
            or 
            "Classify if this movie revieww expresses a positive or negative sentiment."
        )
        init_kwargs["tokenizer_name_or_path"] = model_name

    else:
        init = PromptTuningInit.RANDOM
    return PromptTuningConfig(
        task_type = TaskType.SEQ_CLS,
        num_virtual_tokens = num_virtual_tokens,
        prompt_tuning_init = init,
        **init_kwargs
    )

def _build_prefix_tuning_config(num_virtual_tokens, encoder_hidden_size, prefix_projection):
    """
    Shared by prefix-tuning and p-tuning-v2 - both inject a trainable prefix into the 
    K and V of every transformer layer. `prefix projection` is varible that controls 
    whether the prefix is reparameterized through a small MLP or trained directly.
    """
    from peft import PrefixTuningConfig, TaskType
    
    return PrefixTuningConfig(
        task_type = TaskType.SEQ_CLS,
        num_virtual_tokens = num_virtual_tokens, 
        encoder_hidden_size = encoder_hidden_size, 
        prefix_projection = prefix_projection
    )

def _build_p_tuning_config(num_virtual_tokens, encoder_hidden_size, encoder_num_layers,
                           encoder_dropout, encoder_reparameterization_type):
    """
    p-tuning: a trainable soft tokens are injected into the input embeddings of the first layer, 
    but the soft tokens are generated by the MLP (prompt encoder) instead of being trained directly.
    """
    from peft import PromptEncoderConfig, PromptEncoderReparameterizationType, TaskType
    reparam_type = (
        PromptEncoderReparameterizationType.LSTM
        if encoder_reparameterization_type.upper() == "LSTM"
        else PromptEncoderReparameterizationType.MLP
    )

    return PromptEncoderConfig(
        task_type = TaskType.SEQ_CLS,
        num_virtual_tokens = num_virtual_tokens,
        encoder_hidden_size = encoder_hidden_size,
        encoder_num_layers = encoder_num_layers,
        encoder_dropout = encoder_dropout, 
        encoder_reparameterization_type = reparam_type
    )


def build_prompt_family_model(strategy, model_name, num_virtual_tokens = 20,
                              prompt_tuning_init = "random", prompt_tuning_init_text = None,
                              encoder_hidden_size = 128, encoder_num_layers = 2,
                               encoder_dropout = 0.0, encoder_reparameterization_type = "MLP"):
    """
    """
    if strategy not in PROMPT_FAMILY_STRATEGIES:
        raise TypeError(
            f"Invalid prompt-family strategy: {strategy}, must be one of {PROMPT_FAMILY_STRATEGIES}"
        )
    from peft import get_peft_model
    base_model = AutoModelForSequenceClassification.from_pretrained(
        model_name, num_labels = NUM_LABELS, attn_implementation = "eager"
        )

    if strategy == "prompt-tuning":
        peft_config = _build_prompt_tuning_config(
            model_name, num_virtual_tokens, prompt_tuning_init, prompt_tuning_init_text
        )
    elif strategy == "prefix-tuning":
        peft_config = _build_prefix_tuning_config(
            num_virtual_tokens, encoder_hidden_size, prefix_projection = True
        )

    
        

    return get_peft_model(base_model, peft_config)